feat(hash): add iterator module
Water-Melon/Melon pull request #14
Opened 2023-11-22 17:27 UTC by Jer6y

feat(hash): add iterator module
下面是test:
```c
#include <stdio.h>
#include <stdlib.h>
#include "include/mln_hash.h"

mln_hash_t *h;
typedef struct mln_hash_test_s {
    int    key;
    int    val;
} mln_hash_test_t;

static mln_u64_t calc_handler(mln_hash_t *h, void *key)
{
    return *((int *)key) % h->len;
}

static int cmp_handler(mln_hash_t *h, void *key1, void *key2)
{
    return !(*((int *)key1) - *((int *)key2));
}

static void free_handler(void *val)
{
    printf("free val\n");
    free(val);
}
int hash_it_1(mln_hash_iterator_t* it, void *udata)
{
    int key =*(int *)mln_hash_iterator_key_get(it);
    mln_hash_test_t* v = (mln_hash_test_t *)mln_hash_iterator_value_get(it);
    printf("key:%d value:%d\n",key,v->val);
    return 0;
}

int hash_it_2(mln_hash_iterator_t* it, void *udata)
{
    mln_hash_remove(it->it_belong,it);
    mln_hash_iterator_free(it,M_HASH_F_VAL);
    return 0;
}
void print()
{
    mln_hash_iterate(h,hash_it_1,h);
}
void test()
{
    mln_hash_iterate(h,hash_it_2,h);    
}
int main(int argc, char *argv[])
{
    struct mln_hash_attr hattr;
    mln_hash_test_t *item, *ret;

    hattr.pool = NULL;
    hattr.pool_alloc = NULL;
    hattr.pool_free = NULL;
    hattr.hash = calc_handler;
    hattr.cmp = cmp_handler;
    hattr.free_key = NULL;
    hattr.free_val = free_handler;
    hattr.len_base = 97;
    hattr.expandable = 0;
    hattr.calc_prime = 0;

    if ((h = mln_hash_new(&hattr)) == NULL) {
        fprintf(stderr, "Hash init failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 1;
    item->val = 10;
    mln_hash_iterator_t* it =mln_hash_iterator_new(h,&(item->key),item);
    if (it ==NULL) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }
    mln_hash_insert(h,it);

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 2;
    item->val = 50;
    it =mln_hash_iterator_new(h,&(item->key),item);
    if (it ==NULL) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }
    mln_hash_insert(h,it);
    
    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 1;
    item->val = 40;
    it =mln_hash_iterator_new(h,&(item->key),item);
    if (it ==NULL) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }
    mln_hash_insert(h,it);
    
    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 2;
    item->val = 30;
    it =mln_hash_iterator_new(h,&(item->key),item);
    if (it ==NULL) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }
    mln_hash_insert(h,it);
    
    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 1;
    item->val = 20;
    it =mln_hash_iterator_new(h,&(item->key),item);
    if (it ==NULL) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }
    mln_hash_insert(h,it);
    
    print();
    test();
    printf("==================\n");
    print();
    return 0;
}
```

2023-11-23 05:57 UTC, Water-Melon requested changes

2023-11-23 05:57 UTC, Water-Melon commented on include/mln_hash.h
> +    mln_hash_mgr_t           it_chain;
这里增加的应该是
```c
mln_hash_entry_t        *head;
mln_hash_entry_t        *tail;
mln_hash_entry_t        *iter;
```
mgr那个没必要多一次寻址。
iter是用来记录iterate函数遍历时，当前遍历到了哪个结点，好在remove时直接判断用的。

2023-11-23 05:57 UTC, Water-Melon commented on src/mln_hash.c
> -
return之后的空行保留，这样读代码的人好意识到这里有个返回的分支。
后续的return的空行也就改回来。

2023-11-23 05:57 UTC, Water-Melon commented on src/mln_hash.c
> +
函数开始不用加空行了

2023-11-23 07:21 UTC, Water-Melon requested changes

2023-11-23 07:21 UTC, Water-Melon commented on src/mln_hash.c
> +    mln_move_hash_iterator_chain(h,old_h);
`,`后加空格，所有`,`后的空格都加上

2023-11-23 07:21 UTC, Water-Melon commented on src/mln_hash.c
> +    if((he = h_pre->head) != NULL) {
这里不要用if，因为能进入这个逻辑的必然h_pre->head不为空。
写成
```c
ASSERT(h_pre->head != NULL);
```
然后把if里的语句放到这个语句之后。

2023-11-23 07:21 UTC, Water-Melon commented on src/mln_hash.c
> +
去掉空行

2023-11-23 07:21 UTC, Water-Melon commented on src/mln_hash.c
> +    int  conflit_iter = 0;
这里似乎和红黑树的实现还是不一样。红黑树的移除和释放是两个函数，所以直接移除，然后调整迭代指针指向就好。但哈希表这里是会释放的。也就是说在iterate的回调函数中，在调用了remove后，再次使用key和value的时候会出现访问无效内存的问题。
恐怕这里还要加一组链表，用来缓存即将要被删除的结点。
也即是说，如果被删除结点是遍历的当前结点，则把结点移入即将被删除队列。然后在iterate函数结束前清理那个队列。

2023-11-23 08:46 UTC, Jer6y commented
下面是我的测试过的增删查

```c
#include <stdio.h>
#include <stdlib.h>
#include "Melon/include/mln_hash.h"

mln_hash_t *h;

typedef struct mln_hash_test_s {
    int    key;
    int    val;
} mln_hash_test_t;

int hash_print(void *key, void *val, void *udata)
{
    mln_hash_test_t* v = (mln_hash_test_t *)val;
    printf("key : %d val: %d \n",v->key,v->val);
    return 0;
}

int hash_delete_test_1(void *key, void *val, void *udata)
{
    mln_hash_t* h1 = (mln_hash_t *)udata;
    mln_hash_test_t * v = (mln_hash_test_t *)val;
    mln_hash_remove(h1,(void *)key,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)key,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)key,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)key,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)key,M_HASH_F_VAL);
    v->val = 99;
    return 0;
}

int hash_delete_test_1(void *key, void *val, void *udata)
{
    int k =2 ;
    mln_hash_t* h1 = (mln_hash_t *)udata;
    mln_hash_test_t * v = (mln_hash_test_t *)val;
    mln_hash_remove(h1,(void *)&k,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)&k,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)&k,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)&k,M_HASH_F_VAL);
    mln_hash_remove(h1,(void *)&k,M_HASH_F_VAL);
    return 0;
}

int hash_insert_test_1(void *key, void *val, void *udata)
{
    mln_hash_t* h1 = (mln_hash_t *)udata;
    if(*(int*)key == 1)
    {
        mln_hash_test_t *item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
        if (item == NULL) {
            fprintf(stderr, "malloc failed.\n");
            return -1;
        }
        item->key = 5;
        item->val = 9231;
        if (mln_hash_insert(h1, &(item->key), item) < 0) {
            fprintf(stderr, "insert failed.\n");
            return -1;
        }

    }
    if(*(int*)key == 5)
    {
        printf("5 it in !!!\n");
    }
    
    return 0;
}



static mln_u64_t calc_handler(mln_hash_t *h, void *key)
{
    return *((int *)key) % h->len;
}

static int cmp_handler(mln_hash_t *h, void *key1, void *key2)
{
    return !(*((int *)key1) - *((int *)key2));
}

static void free_handler(void *val)
{
    mln_hash_test_t* v = (mln_hash_test_t *)val;
    printf("free : key: %d val:%d\n",v->key,v->val);
    free(val);
}

int main(int argc, char *argv[])
{
    
    struct mln_hash_attr hattr;
    mln_hash_test_t *item, *ret;

    hattr.pool = NULL;
    hattr.pool_alloc = NULL;
    hattr.pool_free = NULL;
    hattr.hash = calc_handler;
    hattr.cmp = cmp_handler;
    hattr.free_key = NULL;
    hattr.free_val = free_handler;
    hattr.len_base = 97;
    hattr.expandable = 0;
    hattr.calc_prime = 0;

    if ((h = mln_hash_new(&hattr)) == NULL) {
        fprintf(stderr, "Hash init failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 1;
    item->val = 10;
    if (mln_hash_insert(h, &(item->key), item) < 0) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 2;
    item->val = 20;
    if (mln_hash_insert(h, &(item->key), item) < 0) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 3;
    item->val = 30;
    if (mln_hash_insert(h, &(item->key), item) < 0) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 1;
    item->val = 40;
    if (mln_hash_insert(h, &(item->key), item) < 0) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }

    item = (mln_hash_test_t *)malloc(sizeof(mln_hash_test_t));
    if (item == NULL) {
        fprintf(stderr, "malloc failed.\n");
        return -1;
    }
    item->key = 2;
    item->val = 10;
    if (mln_hash_insert(h, &(item->key), item) < 0) {
        fprintf(stderr, "insert failed.\n");
        return -1;
    }

    ret = mln_hash_search(h, &(item->key));
    printf("%p %p\n", ret, item);

    mln_hash_iterate(h,hash_print,h);
    mln_hash_iterate(h,hash_delete_test_1,h);
    printf("====================================\n");
    mln_hash_iterate(h,hash_print,h);

    return 0;
}
```

2023-11-23 10:43 UTC, Water-Melon commented on src/mln_hash.c
> +    mln_hash_t     *old_h   = h;
一样

2023-11-23 10:44 UTC, Water-Melon commented on src/mln_hash.c
> +    he = h_pre->head;
直接这么写吧
```c
mln_hash_entry_t *he = h_pre->head;
```

2023-11-23 10:47 UTC, Water-Melon commented on src/mln_hash.c
> +    int  conflit_iter = 0;
这个变量没必要，直接用he是否为NULL做判断就行，he给个初值NULL

2023-11-23 10:48 UTC, Water-Melon commented on include/mln_hash.h
> +    mln_hash_flag_t          delete_delay;
不要拓展flag，这里直接
```c
mln_u32_t     removed:1;
```

2023-11-23 11:27 UTC, Jer6y commented on include/mln_hash.h
> +    mln_hash_flag_t          delete_delay;
这里添加这个主要是用户在延迟释放的时候需要指定释放方式 这里添加标记用这种方式 顺便就记录了用户延迟释放的方式

2023-11-23 11:29 UTC, Jer6y commented on src/mln_hash.c
> +    mln_hash_t     *old_h   = h;
这个变量是因为我添加了一个函数 在expand 和 reduce 的时候需要给新旧哈希表  这样才可以把迭代链表添加到新的表里面去

2023-11-23 16:08 UTC, Water-Melon requested changes

2023-11-24 05:14 UTC, Water-Melon commented
This PR is closed. Please refer to #15.

2023-11-24 05:14 UTC, closed without merging